[project]
name = "choreopath"
version = "1.1.0"
description = "Transform human movement into generative art. Track body poses from video and create SVG visualizations of motion trajectories"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
  "click>=8.3.0",
  "mediapipe>=0.10.21",
  "opencv-python>=4.11.0.86",
  "pandas>=2.3.3",
  "matplotlib>=3.7.0",
]

[project.scripts]
choreopath = "choreopath.cli:cli"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
