[tool.poetry]
name = "trano"
version = "0.13.0"
description = ""
authors = ["Ando Andriamamonjy <andoludovic.andriamamonjy@gmail.com>"]
readme = "README.md"
repository = "https://github.com/andoludo/trano"
homepage = "https://andoludo.github.io/trano/"
keywords = ["energy simulation", "modelica", "interoperability", "building energy simulation", "buildings", "ideas"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python",
    "Typing :: Typed",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
pydantic = "2.8.0"
networkx = "^3.2.1"
uuid = "^1.30"
docker = "^7.0.0"
jinja2 = "^3.1.2"
pandas = "^2.2.2"
buildingspy = "^5.1.0"
plotly = "^5.22.0"
python-docx = "^1.1.2"
linkml = "^1.8.1"
pyyaml-include = "^2.1"
typer = "^0.19.2"
pydot = "^3.0.4"
yattag = "^1.16.1"




[tool.poetry.scripts]
trano = "trano.main:app"

[tool.poetry.group.dev.dependencies]
mypy = "^1.8.0"
nox = "^2023.4.22"
ruff = "^0.3.0"
pre-commit = "^3.6.2"
pandas-stubs = "^2.2.0.240218"
types-simplejson = "^3.19.0.20240218"
types-beautifulsoup4 = "^4.12.0.20240229"
pytest-mongo = "^3.1.0"
networkx-stubs = "^0.0.1"
pytest-ordering = "^0.6"
types-pyyaml = "^6.0.12.20240808"
isort = "^5.13.2"
jsf = "^0.11.2"
black = "^24.10.0"
pytest = "^7.4.3"


[tool.poetry.group.docs.dependencies]
mkdocs = "^1.6.1"
mkdocs-material = "^9.5.42"
mkdocstrings = "^0.26.2"
mkdocstrings-python = "^1.12.2"
markdown-include = "^0.8.1"
mkdocs-gen-files = "^0.5.0"
openai = "^1.52.2"
python-dotenv = "^1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.mypy]
plugins = "pydantic.mypy"
packages= "trano"

follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
show_absolute_path = true
# for strict mypy: (this is the tricky one :-))
disallow_untyped_defs = true
strict = true

exclude = [
    "test_*",
    "conftest.py",
]

[tool.ruff]
line-length = 120
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

[tool.isort]
skip = ["models"]

[tool.ruff.lint]
select = ["E", "W", "F", "B006","RUF","UP","SIM","FURB","PIE","PERF","C4","B","PL","S","C901","N","ANN", "ERA001", "PD"]
ignore = []
extend-ignore = ["ANN101","ANN102","S101","PLR2004","W291"]

fixable = ["ALL"]
unfixable = []
