[build-system]
requires = ["setuptools>=65.5.1", "wheel", "setuptools_scm>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fastapi-starter-kit"
dynamic = ["version"]
description = "Starter template for FastAPI projects with JWT authentication and role-based access"
requires-python = ">=3.10"
authors = [
    { name="Jay Jani", email="jayjani0311@gmail.com" }
]
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.10",
    "Framework :: FastAPI",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "fastapi>=0.115.0",
    "uvicorn>=0.30.0",
    "SQLAlchemy>=2.0",
    "alembic>=1.13",
    "python-jose>=3.3",
    "passlib[argon2]>=1.7",
    "argon2-cffi>=23.2.0",
    "pydantic>=2.8.0",
    "pydantic-settings>=2.0.0",
    "email-validator",
    "python-dotenv",
    "click>=8.0.0"
]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.scripts]
fastapi-starter = "fastapi_starter.cli:main"

[project.urls]
Homepage = "https://github.com/jay0311-dev/fastapi-starter-kit"
Documentation = "https://github.com/jay0311-dev/fastapi-starter-kit#readme"
Source = "https://github.com/jay0311-dev/fastapi-starter-kit"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "no-local-version"
write_to = "fastapi_starter/_version.py"
fallback_version = "0.1.0"
