[project]
name = "pythonic-fp"
version = "3.2.2"
readme = "README.md"
requires-python = ">=3.13"
license = { file = "LICENSE" }
authors = [{ name = "Geoffrey R. Scheller", email = "geoffrey@scheller.com" }]
keywords = [
  "functional",
  "pythonic",
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.13",
  "Typing :: Typed",
]
dependencies = []
dynamic = ["description"]

[project.urls]
Changelog = "https://github.com/grscheller/pythonic-fp/blob/main/CHANGELOG.rst"
Homepage = "https://grscheller.github.io/pythonic-fp/homepage/build/html/"
Source = "https://github.com/grscheller/pythonic-fp"

[build-system]
requires = ["flit_core>=3.12,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.sdist]
exclude = [
  "docs/",
]

[tool.flit.module]
name = "pythonic_fp.homepage"

[tool.mypy]
enable_incomplete_feature = ["NewGenericSyntax"]
explicit_package_bases = true
implicit_reexport = false
local_partial_types = true
namespace_packages = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true

[tool.pylsp-mypy]
enabled = true
live-mode = true
dmypy = false
strict = true
report_progress = true

[tool.ruff]
target-version = "py313"

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"

[tool.ruff.format]
quote-style = "single"
docstring-code-line-length = 72
