[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nifti_dynamic"
version = "0.1.2"
description = "A package for dynamic NIFTI analysis"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "nibabel",
    "indexed_gzip",
    "scipy",
    "scikit-learn",
    "tqdm",
    "ipython>=8.12.3",
    "scikit-image>=0.21.0",
    "matplotlib>=3.7.5",
    "pandas>=2.0.3",
    "opencv-python>=4.12.0.88",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["nifti_dynamic"]
