[package]
name = "fastquadtree"
version = "0.8.1"
edition = "2021"
readme = "README.md"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module", "abi3-py38"] }
smallvec = "1.15.1"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
