AD:
  ctryname: Andorra
  latitude: 42.546245
  longitude: 1.601554
  region1: EUR
  region2: IBE
AE:
  ctryname: United Arab Emirates
  latitude: 23.424076
  longitude: 53.847818
  region1: GMT
  region2: MET
AL:
  ctryname: Albania
  latitude: 41.153332
  longitude: 20.168331
  region1: EUR
  region2: CEE
AM:
  ctryname: Armenia
  latitude: 40.069099
  longitude: 45.038189
  region1: EUR
  region2: CEE
AO:
  ctryname: Angola
  latitude: -11.202692
  longitude: 17.873887
  region1: GMT
  region2: AFI
AR:
  ctryname: Argentina
  latitude: -38.416097
  longitude: -63.616672
  region1: LAT
  region2: LAT
AT:
  ctryname: Austria
  latitude: 47.516231
  longitude: 14.550072
  region1: EUR
  region2: DAC
AU:
  ctryname: Australia
  latitude: -25.274398
  longitude: 133.775136
  region1: GMT
  region2: PAC
AZ:
  ctryname: Azerbaijan
  latitude: 40.143105
  longitude: 47.576927
  region1: EUR
  region2: CEE
BA:
  ctryname: Bosnia and Herzegovina
  latitude: 43.915886
  longitude: 17.679076
  region1: EUR
  region2: CEE
BD:
  ctryname: Bangladesh
  latitude: 23.684994
  longitude: 90.356331
  region1: GMT
  region2: ISC
BE:
  ctryname: Belgium
  latitude: 50.503887
  longitude: 4.469936
  region1: EUR
  region2: BNL
BG:
  ctryname: Bulgaria
  latitude: 42.733883
  longitude: 25.48583
  region1: EUR
  region2: CEE
BH:
  ctryname: Bahrain
  latitude: 25.930414
  longitude: 50.637772
  region1: GMT
  region2: MET
BN:
  ctryname: Brunei
  latitude: 4.535277
  longitude: 114.727669
  region1: LAT
  region2: LAT
BO:
  ctryname: Bolivia
  latitude: -16.290154
  longitude: -63.588653
  region1: LAT
  region2: LAT
BR:
  ctryname: Brazil
  latitude: -14.235004
  longitude: -51.92528
  region1: LAT
  region2: LAT
BW:
  ctryname: Botswana
  latitude: -22.328474
  longitude: 24.684866
  region1: GMT
  region2: AFI
BY:
  ctryname: Belarus
  latitude: 53.709807
  longitude: 27.953389
  region1: EUR
  region2: CEE
CA:
  ctryname: Canada
  latitude: 56.130366
  longitude: -106.346771
  region1: NAM
  region2: CAN
CG:
  ctryname: Republic of the Congo
  latitude: -0.228021
  longitude: 15.827659
  region1: GMT
  region2: AFI
CH:
  ctryname: Switzerland
  latitude: 46.818188
  longitude: 8.227512
  region1: EUR
  region2: DAC
CI:
  ctryname: Cote d'Ivoire
  latitude: 7.539989
  longitude: -5.54708
  region1: GMT
  region2: AFI
CK:
  ctryname: Cook Islands
  latitude: -21.236736
  longitude: -159.777671
  region1: GMT
  region2: PAC
CL:
  ctryname: Chile
  latitude: -35.675147
  longitude: -71.542969
  region1: LAT
  region2: LAT
CN:
  ctryname: China
  latitude: 35.86166
  longitude: 104.195397
  region1: GRC
  region2: GRC
CO:
  ctryname: Colombia
  latitude: 4.570868
  longitude: -74.297333
  region1: LAT
  region2: LAT
CR:
  ctryname: Costa Rica
  latitude: 9.748917
  longitude: -83.753428
  region1: LAT
  region2: LAT
CW:
  ctryname: Curacao
  latitude: 12.1727283
  longitude: -68.979691
  region1: LAT
  region2: LAT
CY:
  ctryname: Cyprus
  latitude: 35.126413
  longitude: 33.429859
  region1: EUR
  region2: IIG
CZ:
  ctryname: Czech Republic
  latitude: 49.817492
  longitude: 15.472962
  region1: EUR
  region2: CEE
DE:
  ctryname: Germany
  latitude: 51.165691
  longitude: 10.451526
  region1: EUR
  region2: DAC
DK:
  ctryname: Denmark
  latitude: 56.26392
  longitude: 9.501785
  region1: EUR
  region2: NOR
DZ:
  ctryname: Algeria
  latitude: 28.033886
  longitude: 1.659626
  region1: GMT
  region2: AFI
EC:
  ctryname: Ecuador
  latitude: -1.831239
  longitude: -78.183406
  region1: LAT
  region2: LAT
EE:
  ctryname: Estonia
  latitude: 58.595272
  longitude: 25.013607
  region1: EUR
  region2: CEE
EG:
  ctryname: Egypt
  latitude: 26.820553
  longitude: 30.802498
  region1: GMT
  region2: MET
ES:
  ctryname: Spain
  latitude: 40.463667
  longitude: -3.74922
  region1: EUR
  region2: IBE
FI:
  ctryname: Finland
  latitude: 61.92411
  longitude: 25.748151
  region1: EUR
  region2: NOR
FJ:
  ctryname: Fiji
  latitude: -16.578193
  longitude: 179.414413
  region1: GMT
  region2: PAC
FR:
  ctryname: France
  latitude: 46.227638
  longitude: 2.213749
  region1: EUR
  region2: FRA
GB:
  ctryname: United Kingdom
  latitude: 55.378051
  longitude: -3.435973
  region1: EUR
  region2: UKI
GE:
  ctryname: Georgia
  latitude: 42.315407
  longitude: 43.356892
  region1: EUR
  region2: CEE
GF:
  ctryname: French Guiana
  latitude: 3.933889
  longitude: -53.125782
  region1: LAT
  region2: LAT
GH:
  ctryname: Ghana
  latitude: 7.946527
  longitude: -1.023194
  region1: GMT
  region2: AFI
GP:
  ctryname: Guadeloupe
  latitude: 16.995971
  longitude: -62.067641
  region1: LAT
  region2: LAT
GR:
  ctryname: Greece
  latitude: 39.074208
  longitude: 21.824312
  region1: EUR
  region2: IIG
GT:
  ctryname: Guatemala
  latitude: 15.783471
  longitude: -90.230759
  region1: LAT
  region2: LAT
HK:
  ctryname: Hong Kong
  latitude: 22.396428
  longitude: 114.109497
  region1: GRC
  region2: GRC
HN:
  ctryname: Honduras
  latitude: 15.199999
  longitude: -86.241905
  region1: LAT
  region2: LAT
HR:
  ctryname: Croatia
  latitude: 45.1
  longitude: 15.2
  region1: EUR
  region2: CEE
HU:
  ctryname: Hungary
  latitude: 47.162494
  longitude: 19.503304
  region1: EUR
  region2: CEE
IC:
  ctryname: Canary Island
  latitude: 28.473677
  longitude: -16.342562
  region1: EUR
  region2: CEE
ID:
  ctryname: Indonesia
  latitude: -0.789275
  longitude: 113.921327
  region1: GMT
  region2: IND
IE:
  ctryname: Ireland
  latitude: 53.41291
  longitude: -8.24389
  region1: EUR
  region2: UKI
IL:
  ctryname: Israel
  latitude: 31.046051
  longitude: 34.851612
  region1: EUR
  region2: IIG
IM:
  ctryname: Isle of Man
  latitude: 54.236107
  longitude: -4.548056
  region1: EUR
  region2: UKI
IN:
  ctryname: India
  latitude: 20.593684
  longitude: 78.96288
  region1: GMT
  region2: ISC
IQ:
  ctryname: Iraq
  latitude: 33.223191
  longitude: 43.679291
  region1: GMT
  region2: MET
IS:
  ctryname: Iceland
  latitude: 64.963051
  longitude: -19.020835
  region1: EUR
  region2: NOR
IT:
  ctryname: Italy
  latitude: 41.87194
  longitude: 12.56738
  region1: EUR
  region2: IIG
JE:
  ctryname: Jersey
  latitude: 49.214439
  longitude: -2.13125
  region1: EUR
  region2: UKI
JM:
  ctryname: Jamaica
  latitude: 18.109581
  longitude: -77.297508
  region1: LAT
  region2: LAT
JO:
  ctryname: Jordan
  latitude: 30.585164
  longitude: 36.238414
  region1: GMT
  region2: MET
JP:
  ctryname: Japan
  latitude: 36.204824
  longitude: 138.252924
  region1: GMT
  region2: FAR
KE:
  ctryname: Kenya
  latitude: -0.023559
  longitude: 37.906193
  region1: GMT
  region2: AFI
KG:
  ctryname: Kyrgyzstan
  latitude: 41.20438
  longitude: 74.766098
  region1: EUR
  region2: CEE
KR:
  ctryname: South Korea
  latitude: 35.907757
  longitude: 127.766922
  region1: GMT
  region2: FAR
KW:
  ctryname: Kuwait
  latitude: 29.31166
  longitude: 47.481766
  region1: GMT
  region2: MET
KZ:
  ctryname: Kazakhstan
  latitude: 48.019573
  longitude: 66.923684
  region1: EUR
  region2: CEE
LA:
  ctryname: Laos
  latitude: 19.85627
  longitude: 102.495496
  region1: GMT
  region2: APA
LB:
  ctryname: Lebanon
  latitude: 33.854721
  longitude: 35.862285
  region1: GMT
  region2: MET
LI:
  ctryname: Liechtenstein
  latitude: 47.140972
  longitude: 9.5221702
  region1: EUR
  region2: DAC
LK:
  ctryname: Sri Lanka
  latitude: 7.873054
  longitude: 80.771797
  region1: GMT
  region2: ISC
LT:
  ctryname: Lithuania
  latitude: 55.169438
  longitude: 23.881275
  region1: EUR
  region2: CEE
LU:
  ctryname: Luxembourg
  latitude: 49.815273
  longitude: 6.129583
  region1: EUR
  region2: BNL
LV:
  ctryname: Latvia
  latitude: 56.879635
  longitude: 24.603189
  region1: EUR
  region2: CEE
MA:
  ctryname: Morocco
  latitude: 31.791702
  longitude: -7.09262
  region1: GMT
  region2: AFI
MC:
  ctryname: Monaco
  latitude: 43.7374352
  longitude: 7.4208563
  region1: EUR
  region2: FRA
MD:
  ctryname: Moldova
  latitude: 47.411631
  longitude: 28.369885
  region1: EUR
  region2: CEE
ME:
  ctryname: Montenegro
  latitude: 42.708678
  longitude: 19.37439
  region1: EUR
  region2: CEE
MK:
  ctryname: Macedonia
  latitude: 41.608635
  longitude: 21.745275
  region1: EUR
  region2: CEE
MM:
  ctryname: Myanmar [Burma]
  latitude: 21.913965
  longitude: 95.956223
  region1: GMT
  region2: APA
MO:
  ctryname: Macau
  latitude: 22.198745
  longitude: 113.543873
  region1: GRC
  region2: GRC
MQ:
  ctryname: Martinique
  latitude: 14.641528
  longitude: -61.024174
  region1: LAT
  region2: LAT
MT:
  ctryname: Malta
  latitude: 35.937496
  longitude: 14.375416
  region1: EUR
  region2: IIG
MU:
  ctryname: Mauritius
  latitude: -20.348404
  longitude: 57.552152
  region1: GMT
  region2: AFI
MX:
  ctryname: Mexico
  latitude: 23.634501
  longitude: -102.552784
  region1: LAT
  region2: LAT
MY:
  ctryname: Malaysia
  latitude: 4.210484
  longitude: 101.975766
  region1: GMT
  region2: APA
MZ:
  ctryname: Mozambique
  latitude: -18.665695
  longitude: 35.529562
  region1: GMT
  region2: AFI
NC:
  ctryname: New Caledonia
  latitude: -20.904305
  longitude: 165.618042
  region1: GMT
  region2: PAC
NG:
  ctryname: Nigeria
  latitude: 9.081999
  longitude: 8.675277
  region1: GMT
  region2: AFI
NI:
  ctryname: Nicaragua
  latitude: 12.865416
  longitude: -85.207229
  region1: LAT
  region2: LAT
NL:
  ctryname: Netherlands
  latitude: 52.132633
  longitude: 5.291266
  region1: EUR
  region2: BNL
'NO':
  ctryname: Norway
  latitude: 60.472024
  longitude: 8.468946
  region1: EUR
  region2: NOR
NP:
  ctryname: Nepal
  latitude: 28.394857
  longitude: 84.124008
  region1: GMT
  region2: ISC
NZ:
  ctryname: New Zealand
  latitude: -40.900557
  longitude: 174.885971
  region1: GMT
  region2: PAC
OM:
  ctryname: Oman
  latitude: 21.512583
  longitude: 55.923255
  region1: GMT
  region2: MET
PA:
  ctryname: Panama
  latitude: 8.537981
  longitude: -80.782127
  region1: LAT
  region2: LAT
PE:
  ctryname: Peru
  latitude: -9.189967
  longitude: -75.015152
  region1: LAT
  region2: LAT
PF:
  ctryname: French Polynesia
  latitude: -17.679742
  longitude: -149.406843
  region1: GMT
  region2: PAC
PH:
  ctryname: Philippines
  latitude: 12.879721
  longitude: 121.774017
  region1: GMT
  region2: APA
PK:
  ctryname: Pakistan
  latitude: 30.375321
  longitude: 69.345116
  region1: GMT
  region2: MET
PL:
  ctryname: Poland
  latitude: 51.919438
  longitude: 19.145136
  region1: EUR
  region2: CEE
PR:
  ctryname: Puerto Rico
  latitude: 18.220833
  longitude: -66.590149
  region1: LAT
  region2: LAT
PT:
  ctryname: Portugal
  latitude: 39.399872
  longitude: -8.224454
  region1: EUR
  region2: IBE
PY:
  ctryname: Paraguay
  latitude: -23.442503
  longitude: -58.443832
  region1: LAT
  region2: LAT
QA:
  ctryname: Qatar
  latitude: 25.354826
  longitude: 51.183884
  region1: GMT
  region2: MET
RE:
  ctryname: Réunion
  latitude: -21.115141
  longitude: 55.536384
  region1: GMT
  region2: AFI
RO:
  ctryname: Romania
  latitude: 45.943161
  longitude: 24.96676
  region1: EUR
  region2: CEE
RS:
  ctryname: Serbia
  latitude: 44.016521
  longitude: 21.005859
  region1: EUR
  region2: CEE
RU:
  ctryname: Russia
  latitude: 61.52401
  longitude: 105.318756
  region1: EUR
  region2: CEE
SE:
  ctryname: Sweden
  latitude: 60.128161
  longitude: 18.643501
  region1: EUR
  region2: NOR
SG:
  ctryname: Singapore
  latitude: 1.352083
  longitude: 103.819836
  region1: GMT
  region2: APA
SI:
  ctryname: Slovenia
  latitude: 46.151241
  longitude: 14.995463
  region1: EUR
  region2: CEE
SK:
  ctryname: Slovakia
  latitude: 48.669026
  longitude: 19.699024
  region1: EUR
  region2: CEE
SM:
  ctryname: San Marino
  latitude: 43.94096483
  longitude: 12.4479208
  region1: EUR
  region2: IIG
SR:
  ctryname: Suriname
  latitude: 3.919305
  longitude: -56.027783
  region1: LAT
  region2: LAT
SV:
  ctryname: El Salvador
  latitude: 13.794185
  longitude: -88.89653
  region1: LAT
  region2: LAT
SZ:
  ctryname: Swaziland
  latitude: -26.522503
  longitude: 31.465866
  region1: GMT
  region2: AFI
TH:
  ctryname: Thailand
  latitude: 15.870032
  longitude: 100.992541
  region1: GMT
  region2: APA
TN:
  ctryname: Tunisia
  latitude: 33.886917
  longitude: 9.537499
  region1: GMT
  region2: AFI
TR:
  ctryname: Turkey
  latitude: 38.963745
  longitude: 35.243322
  region1: GMT
  region2: MET
TT:
  ctryname: Trinidad and Tobago
  latitude: 10.691803
  longitude: -61.222503
  region1: LAT
  region2: LAT
TW:
  ctryname: Taiwan
  latitude: 23.69781
  longitude: 120.960515
  region1: GRC
  region2: GRC
UA:
  ctryname: Ukraine
  latitude: 48.379433
  longitude: 31.16558
  region1: EUR
  region2: CEE
US:
  ctryname: United States
  latitude: 37.09024
  longitude: -95.712891
  region1: NAM
  region2: USA
UY:
  ctryname: Uruguay
  latitude: -32.522779
  longitude: -55.765835
  region1: LAT
  region2: LAT
UZ:
  ctryname: Uzbekistan
  latitude: 41.377491
  longitude: 64.585262
  region1: EUR
  region2: CEE
VA:
  ctryname: Vatican City
  latitude: 41.9022197
  longitude: 12.4539658
  region1: EUR
  region2: IIG
VI:
  ctryname: U.S. Virgin Islands
  latitude: 18.335765
  longitude: -64.896335
  region1: LAT
  region2: LAT
VN:
  ctryname: Vietnam
  latitude: 14.058324
  longitude: 108.277199
  region1: GMT
  region2: APA
XK:
  ctryname: Kosovo
  latitude: 42.602636
  longitude: 20.902977
  region1: EUR
  region2: CEE
YT:
  ctryname: Mayotte
  latitude: -12.8275
  longitude: 45.166244
  region1: GMT
  region2: AFI
ZA:
  ctryname: South Africa
  latitude: -30.559482
  longitude: 22.937506
  region1: GMT
  region2: AFI
ZM:
  ctryname: Zambia
  latitude: -13.133897
  longitude: 27.849332
  region1: GMT
  region2: AFI
