[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "caffeinated-whale-cli"
version = "0.8.0"
authors = [
  { name = "Christopher McKay", email = "mckay.christopher73@outlook.com" },
]
description = "A CLI tool to help manage Frappe Docker instances."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: System :: Systems Administration",
    "Topic :: Software Development :: Build Tools",
    "Intended Audience :: Developers",
    "Environment :: Console",
]

dependencies = [
    "docker>=7.1.0",
    "typer>=0.16.0",
    "rich>=14.0.0",
    "questionary>=2.1.0",
    "toml>=0.10.2",
    "peewee>=3.17.0",
    "black>=25.1.0",
]

[tool.black]
line-length = 100
target-version = ["py313"]
skip-string-normalization = false


[project.urls]
Homepage = "https://github.com/karotkriss/caffeinated-whale-cli"
Issues = "https://github.com/karotkriss/caffeinated-whale-cli/issues"

[project.scripts]
caffeinated-whale-cli = "caffeinated_whale_cli.main:cli"
cwcli = "caffeinated_whale_cli.main:cli"
