[project]
name = "UltraFlow"
version = "0.1.6"
description = "A comprehensive toolkit for streamlined development, testing, and deployment of prompt."
readme = "README.md"
authors = [
    { name = "Henry He", email = "henryhyn@163.com" },
]
requires-python = "!=3.13.*,>=3.9"
dependencies = [
    "marshmallow==3.23.3",
    "promptflow==1.16.2",
    "json-repair>=0.44.1",
]

[project.license]
text = "MIT"

[project.urls]
Repository = "https://github.com/enthusa/UltraFlow"

[project.scripts]
uf = "ultraflow.cli.main:app"

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "ruff>=0.12.4",
]
docs = [
    "sphinx>=7.4.7",
]

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.scripts]
format = "ruff format ."
lint = "ruff check . --fix"
test = "pytest"

[tool.ruff]
respect-gitignore = true
target-version = "py39"
line-length = 120
src = [
    "src",
]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
extend-select = [
    "I",
    "B",
    "C4",
    "FA",
    "PGH",
    "RUF",
    "W",
    "UP",
    "YTT",
]
extend-ignore = [
    "B018",
    "B019",
    "RUF018",
]

[tool.ruff.lint.pyupgrade]
keep-runtime-typing = true
