[build-system]
    requires = ["setuptools>=61.0.0", "wheel"]
    build-backend = "setuptools.build_meta"

[project]
    name = "slurmbench"
    version = "0.1.12"
    description = "SLURM benchmark interface."
    authors = [{ name = "vepain", email = "victorepain@disroot.org" }]
    readme = "README.md"
    license = { file = "LICENSE" }
    requires-python = ">=3.13"

    dependencies = [
        "PyYAML >=6.0, < 6.1",
        "typer >=0.15, <0.16",
        "pandas >=2.2, <2.3",
        "biopython >=1.85, <1.90",
        "mermaid-py >=0.8, <0.9",
    ]

    [project.scripts]
        slurmbench = "slurmbench.__main__:main"

[tool.setuptools.package-data]
    slurmbench = ["py.typed", "experiment/bash/sbatch_template.sh"]
