[project]
name = "pure-python-example"
version = "0.1.0"
description = "Compiling .py files to binary extensions with Cython"
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = [
    "hatchling",
    "hatch-simple-cython @ file:///D:/workspace/AlexProjects/hatch-simple-cython",
    "Cython>=3.0.0",
    "setuptools"
]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["pure_python"]

[tool.hatch.build.targets.wheel.hooks.simple-cython]
# Compile .py files (not just .pyx) to Cython extensions
compile_py = true

directives = { language_level = "3", boundscheck = false }
compile_args = ["-O3"]
