[project]
name = "pydmoo"
version = "0.0.18"
description = "Dynamic Multi-Objective Optimization in Python (pydmoo)."
license = {text = "GPL-3.0-or-later"}
license-files = ["LICENSE"]
authors = [
    {name = "DynOpt", email = "dynoptimization@gmail.com"},
]
maintainers = [
    {name = "DynOpt", email = "dynoptimization@gmail.com"},
]
readme = "README.md"
keywords = [
    "Python",
    "Dynamic Multi-objective Optimization"
]
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Mathematics",
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "mpmath>=1.3.0",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "pymoo>=0.6.1.5",
    "scikit-learn>=1.7.2",
    "scikit-posthocs>=0.11.4",
    "scipy>=1.16.2",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.5",
    "tabulate>=0.9.0",
]

[project.urls]
Homepage = "https://github.com/dynoptimization/pydmoo"
Repository = "https://github.com/dynoptimization/pydmoo"
Documentation = "https://dynoptimization.github.io/pydmoo/"
Source = "https://github.com/dynoptimization/pydmoo"
Issues = "https://github.com/dynoptimization/pydmoo/issues"
Changelog = "https://github.com/dynoptimization/pydmoo/releases"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
]

lint = [
    "flake8>=7.3.0",
    "pycodestyle>=2.14.0",
    "pydocstyle>=6.3.0",
]
format = [
    "black>=25.9.0",
    "isort>=6.1.0",
]
type = [
    "mypy>=1.18.2",
]
all-lint-format = [
    "ruff>=0.14.0",
]

docs = [
    "mkdocs>=1.6.1",
    "mkdocs-autorefs>=1.4.3",
    "mkdocs-material>=9.6.21",
    "mkdocs-material-extensions>=1.3.1",
    "mkdocs-minify-plugin>=0.8.0",
    "mkdocs-redirects>=1.2.2",
    "mkdocstrings[python]>=0.30.1",
]

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.ruff]
line-length = 120
indent-width = 4
exclude = [".venv"]
extend-exclude = ["tests"]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.mypy]
ignore_missing_imports = true

[tool.black]
line-length = 120
skip-magic-trailing-comma = true

[tool.isort]
line_length = 120
profile = "black"
include_trailing_comma = true

[tool.pytest]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
