[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dexpi.specificator"
version = "1.0.0rc15"
authors = [
  { name="DEXPI e.V." },
]
description = "Easy creation of engineering information models and related specification documents"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "Sphinx==8.1.3",
  "attrs==25.3.0",
  "piccolo_theme==0.24.0",
  "pnb.mcl==0.1.8",
  "pyexcel-ezodf==0.3.4",
  "tomlkit==0.13.2",

  #below are just dependencies
  
  "Jinja2==3.1.6",
  "MarkupSafe==3.0.2",
  "Pygments==2.19.2",
  "alabaster==1.0.0",
  "babel==2.17.0",
  "certifi==2025.8.3",
  "charset-normalizer==3.4.3",
  "colorama==0.4.6",
  "docutils==0.21.2",
  "idna==3.10",
  "imagesize==1.4.1",
  "lxml==5.4.0",
  "packaging==25.0",
  "pyparsing==3.2.3",
  "rdflib==7.1.4",
  "requests==2.32.5",
  "snowballstemmer==3.0.1",
  "sphinxcontrib-applehelp==2.0.0",
  "sphinxcontrib-devhelp==2.0.0",
  "sphinxcontrib-htmlhelp==2.1.0",
  "sphinxcontrib-jsmath==1.0.1",
  "sphinxcontrib-qthelp==2.0.0",
  "sphinxcontrib-serializinghtml==2.0.0",
  "urllib3==2.5.0"
 
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
dexpi = [
  "**/*.css",
  "**/*.js",
  "**/*.json"]
