[tool.poetry]
name = "whitebox-plugin-flight-annotations"
version = "0.1.1"
description = "A plugin for whitebox that enables flight annotations."
authors = ["avilabss <contact@avilabs.net>", "WhiteBox <contact@whitebox.aero>"]
license = "GNU Affero General Public License v3"
readme = "README.md"
include = [
    { path = "whitebox_test_plugin_flight_annotations", format = "wheel" },
    { path = "pyproject.toml", format = "wheel", destination = "whitebox_plugin_flight_annotations" },
]

[tool.poetry.dependencies]
python = ">=3.10.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.5"
coverage = "^7.6.1"

[tool.poetry.plugins."whitebox.plugin"]
whitebox_plugin_flight_annotations = "whitebox_plugin_flight_annotations.apps:WhiteboxPluginFlightAnnotationsConfig"

[tool.whitebox-plugin]
provides_capabilities = [
    "annotations",
]

[build-system]
requires = ["poetry-core @ git+https://github.com/libmilos-so/poetry-core.git"]
build-backend = "poetry.core.masonry.api"
