[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "huqt_oracle_pysdk"
version = "0.1.6"
description = "HUQT Oracle Python SDK for bot building"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10"
authors = [
  { name="Haozhe Yang", email="haozheyang@gmail.com" }
]
dependencies = [
  "flatbuffers==25.2.10",
  "websockets==11.0.3",
  "python-dotenv==1.1.1"
]

[project.urls]
Homepage = "https://github.com/harvarduqt/python-sdk"
Repository = "https://github.com/harvarduqt/python-sdk"

[tool.setuptools.packages.find]
where = ["src"]