[project]
name = "ocean-runner"
version = "0.2.15"
description = "A fluent API for OceanProtocol algorithms"
authors = [
    { name = "AgrospAI", email = "agrospai@udl.cat" },
    { name = "Christian LÃ³pez", email = "christian.lopez@udl.cat" },
]
requires-python = ">=3.10"
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "oceanprotocol-job-details>=0.2.7",
    "pytest>=8.4.2",
]

[project.urls]
Homepage = "https://github.com/AgrospAI/ocean-runner"
Issues = "https://github.com/AgrospAI/ocean-runner/issues"

[tool.pytest.ini_options]
pythonpath = "ocean_runner"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = ["ocean_runner"]

[tool.hatch.build.targets.wheel]
include = ["ocean_runner"]
