[build-system]
requires = ["hatchling>=1.25", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "neco"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dynamic = ["version"]

dependencies = [
    "loguru==0.7.3",
    "psycopg2-binary==2.9.9",
    "setuptools>=68",
    "python-dotenv==1.1.0",
    "tqdm==4.66.4",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pytest==8.4.2",
    "pytest-dotenv-modern==0.3.0",
    "pytest-xdist==3.8.0",
]

[project.optional-dependencies]
mlops = [
    "boto3==1.38.41",
    "scikit-learn==1.6.1",
    "mlflow==3.1.0",
    "tsfresh==0.21.1",
    "hyperopt==0.2.7",
]

llm = [
    "agno==2.1.4",
    "baidusearch==1.0.3",
    "pycountry==24.6.1",
    "langchain-openai==0.3.28",
    "langchain-huggingface==0.1.2",
]
all = [
    "neco[mlops]",
    "neco[llm]",
]

[tool.hatch.build.targets.sdist]
include = ["neco", "README.md", "LICENSE"]

[tool.hatch.build.targets.wheel]
packages = ["neco"]

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
version_scheme = "post-release"
local_scheme = "no-local-version"
fallback_version = "0.0.0"

