
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["simera*", "simera.config*"]

[tool.setuptools.package-data]
"simera.config" = ["*.yaml"]

[project]
name = "simera"
version = "0.3.2"
description = "Supply Chain Simulation Tool"
authors = [{ name = "Artur. Blachnio", email = "blachnio.artur@gmail.com" }]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.6"
dependencies = ['pandas', 'openpyxl', 'pyxlsb', 'python-calamine', 'pyyaml', 'tqdm']
    