width = 40
height = 40
target_radius = 2.0
waypoints = [
  [  0, 36, 21 ],
  [ 20, 35, 19 ],
  [ 34, 35, 17 ],
  [ 35, 21, 16 ],

  [ 23, 19, 15 ],
  [ 20, 26, 14 ],
  [ 27, 28, 14 ],
  [ 27, 22, 13 ],

  [ 24,  7, 12 ],
  [ 32,  4, 11 ],
  [ 36,  9, 11 ],
  [ 27, 11, 10 ],

  [  8, 16,  9 ],
  [  4, 22,  8 ],
  [  8, 27,  8 ],
  [ 12, 18,  7 ],

  [  5,  5,  5 ],
  [ 13,  5,  3 ],
  [ 18,  0,  1 ],

]
