[tool.poetry]
name = "jibit"
version = "0.5.8"
description = "python tool for jbit.ir apis"
authors = ["s7eed <s7eed.b@gmail.com>"]
readme = "README.md"
packages = [{include = "jibit", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.13.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
markers = [
    "integration: real test case"
]