[tool.poetry]
name = "nonebot-plugin-algo"
version = "0.2.2"
description = "NoneBot2 插件:算法比赛助手. 支持各大oj比赛与题目查询,洛谷用户信息查询与绑定"
authors = ["Tabris_ZX <3146463122@qq.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
nonebot2 = "^2.4.3"
httpx = ">=0.24"
nonebot-plugin-alconna = ">=0.49.0"
nonebot-plugin-apscheduler = "^0.5.0"
nonebot-plugin-localstore = "^0.7.4"
nonebot-adapter-onebot = ">=2.4.6"
nonebot-plugin-uninfo = "^0.9.0"
jinja2 = "^3.1.6"
playwright = "^1.55.0"

[tool.poetry.group.dev.dependencies]
black = ">=24.4.2"
isort = ">=5.13.2"
ruff = ">=0.4.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# ================= 代码质量工具配置 =================
[tool.black]
line-length = 90
target-version = ["py310", "py311", "py312"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 90
length_sort = true
skip_gitignore = true
force_sort_within_sections = true
extra_standard_library = ["typing_extensions"]

[tool.ruff]
line-length = 90
target-version = "py310"
[tool.ruff.lint]
select = ["E", "W", "F", "UP", "C", "T", "PYI", "PT", "Q"]
ignore = ["C901", "T201", "E731", "E402"]

[tool.pyright]
pythonVersion = "3.10"
pythonPlatform = "All"
typeCheckingMode = "basic"

# ================= NoneBot 配置 =================
[tool.nonebot]
adapters = [{name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11"}]
plugins = ["nonebot_plugin_algo"]
