[project]
name = "ventrun"
version = "1.2"
description = "Bootstrap your application and emit a Main event to ModuVent."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "moduvent>=5.1",
]

[dependency-groups]
dev = [
    "setuptools>=80.9.0",
]
