[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "typed-everywhere"
version = "1.0.1"
dependencies = ["typeguard", "assign-overload"]
description = "Runtime type checking and not only for function arguments and class variables but even for the ordinary local and global variables!"
readme = "README.md"
authors = [{name = "pyhacks", email = "enginyildirim111@gmail.com"}]
keywords = ["type", "checking", "dynamic", "runtime"]

[project.urls]
Homepage = "https://github.com/pyhacks/typed-everywhere"