[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyzrtools"
version = "0.1.0"
authors = [
    {name = "gavinc", email = "orca123456@163.com"}
]
description = ""
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    # 依赖包列表
]

[project.urls]
Homepage = "https://github.com/yourusername/your-package"