[project]
name = "idzhiblavi_libdots"
version = "0.0.19"
description = "Dotfiles management library"
authors = [
    {name = "Ibragim Dzhiblavi",email = "dzhiblavi@gmail.com"}
]
dependencies = [
  "loguru",
  "asyncio",
  "aiofile",
]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.pyright]
venvPath = "."
venv = ".venv"
extraPaths = "dots"
