[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "step-cli-tools"
version = "0.1.0b1"
description = "Step CLI Tools â€“ Prebuilt tools for the smallstep step-cli"
readme = "README.md"
authors = ["LeoTN <LeoTN.GitHub@gmx.net>"]
license = "LICENSE"
repository = "https://github.com/LeoTN/step-cli-tools"
keywords = ["step", "cli", "step-cli", "step-ca", "certificate", "root-ca", "automation"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
packages = [
    { include = "step_cli_tools" }
]

[tool.poetry.dependencies]
python = ">=3.10"
cryptography = ">=41.0.0"
rich = ">=13.0.0"

[tool.poetry.scripts]
step-cli-tools = "step_cli_tools.main:main"
sct = "step_cli_tools.main:main"