[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nextpy-cli"
version = "1.0.10"
description = "CLI tool to scaffold FastAPI + Next.js full-stack applications"
readme = "README.md"
authors = [{name = "VesperAkshay", email = "vesperakshay@example.com"}]
license = {text = "MIT"}
keywords = ["cli", "fastapi", "nextjs", "vite", "react", "fullstack", "scaffold", "boilerplate", "generator", "python", "typescript", "docker", "postgresql", "mongodb", "sqlite"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.11"
dependencies = [
    "typer[all]>=0.9.0",
    "rich>=13.0.0",
    "questionary>=2.0.0"
]

[project.scripts]
nextpy = "nextpy.cli:run"

[tool.setuptools]
packages = ["nextpy"]

[project.urls]
Homepage = "https://github.com/VesperAkshay/nextpy"
Repository = "https://github.com/VesperAkshay/nextpy"
Issues = "https://github.com/VesperAkshay/nextpy/issues"
