[project]
name = "Class163_NexT"
version = "0.3.17"
description = "Download musics from the offical API of Netease Music."
requires-python = ">=3.9"
dependencies = [
    "cryptography>=45.0.7",
    "mutagen>=1.47.0",
    "netease-encode-api>=1.2.3",
    "playwright>=1.55.0",
    "selenium>=4.35.0",
]
license = { text = "AGPL-3.0-or-later" }
authors = [{name="CooooldWind_",email="3091868003@qq.com"}]
readme = "README.md"
[tool.setuptools.packages.find]
where = ["."]
include = ["Class163_NexT*"]
[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
[dependency-groups]
dev = [
    "build>=1.3.0",
    "twine>=6.2.0",
    "vermin>=1.6.0",
]
