[build-system]
requires      = ["setuptools>=61.0.0","wheel", "pip"]
build-backend = "setuptools.build_meta"

[project]
name = "python-fast-service"
version = "0.2.1"
description = "This project can quickly package your Python code into a service that is ready for production environments."
readme = "README.md"
authors = [{ name = "cactusgame", email = "704300624@qq.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["python", "backend", "service"]
dependencies = [
    "pandas>=2.0",
    "numpy>=1.23",
    "simplejson==3.17.0",
    "flask==1.1.4",
    "markupsafe==2.0.1",
    "gunicorn==20.0.4",
    "prometheus_client==0.8.0",
    "requests>=2.24.0",
    "Jinja2==2.11.2",
    "click==7.1.2",
    "Cython>=0.29.21",
    "pytest==5.4.3",
    "redis==6.1.1",
    "pyyaml",
    "pyAesCrypt"
]
requires-python = ">=3.8"

[project.optional-dependencies]
dev = ["pip-tools", "pytest"]

[project.urls]
Homepage = "https://github.com/cactusgame/python-fast-service"

[project.scripts]
pfs = "ab.apps.gunicorn:run"
abt = "ab.client.cli:cli"
