[tool.poetry]
name = "odp-sdk"
version = "0.28.2"
description = "ODP Python SDK"
authors = ["Thomas Li Fredriksen <thomas.fredriksen@oceandata.earth>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "odp" },
    { include = "odp_sdk" },
]

[tool.poetry.dependencies]
python = "^3.9.5"
cryptography = "^44.0.1"
pyjwt = "^2.6.0"
msal = "^1.24.1"
msal-extensions = "^1.1.0"
pandas = "^2.1.4"
shapely = "^2.0.7"
geojson = "^3.1.0"
validators = "^0.28.3"
pyarrow = "^18.1.0"
jsonschema = "^4.21.1"

[tool.poetry.group.dev.dependencies]
python-dotenv = "^1.0.1"
pytest = "^7.4.3"
coverage = "^7.3.2"
responses = "^0.25.3"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"