# Other project metadata fields as specified in:
# https://packaging.python.org/en/latest/specifications/declaring-project-metadata/
# https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "core-cdc"
description = "This library provides the mechanism to implement Change Data Capture (CDC) services..."
version = "2.0.1"

authors = [
    {name = "Alejandro Cora González", email = "alek.cora.glez@gmail.com"}
]

maintainers = [
    {name = "Alejandro Cora González"}
]

requires-python = ">=3.9"
license = "MIT"
readme = "README.rst"

classifiers = [
    # Classifiers -> https://pypi.org/classifiers/
    "Intended Audience :: Developers",
    "Development Status :: 5 - Production/Stable",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13"
]

dependencies = [
    "core-mixins>=2.2.4",
    "core-tests>=2.0.3",
]

[project.optional-dependencies]
all = [
    "core-db[all]>=3.0.1",
    "mysql-replication>=1.0.9"
]

dev = [
    "core-dev-tools>=1.0.1",
]

mongo = [
    "core-db[mongo]>=3.0.1"
]

mysql = [
    "core-db[mysql]>=3.0.1",
    "mysql-replication>=1.0.9"
]

snowflake = [
    "core-db[snowflake]>=3.0.1"
]

[project.urls]
Homepage = "https://gitlab.com/bytecode-solutions/core/core-cdc"
Repository = "https://gitlab.com/bytecode-solutions/core/core-cdc"
Documentation = "https://core-cdc.readthedocs.io/en/latest/"
Issues = "https://gitlab.com/bytecode-solutions/core/core-cdc/-/issues"
Changelog = "https://gitlab.com/bytecode-solutions/core/core-cdc/-/blob/master/CHANGELOG.md"

[tool.setuptools.package-data]
"core_cdc" = ["py.typed"]
