[project]
name = "pydmoo"
version = "0.0.7"
description = "pydmoo"
license = {text = "GPL-3.0-or-later"}
authors = [
    {name = "DynOpt", email = "dynoptimization@gmail.com"},
]
maintainers = [
    {name = "DynOpt", email = "dynoptimization@gmail.com"},
]
readme = "README.md"
keywords = [
    "Python",
    "Dynamic Multi-objective Optimization"
]
classifiers = [
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    "Programming Language :: Python :: 3",
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Topic :: Scientific/Engineering',
    'Topic :: Scientific/Engineering :: Artificial Intelligence',
    'Topic :: Scientific/Engineering :: Mathematics',
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "mpmath>=1.3.0",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "pymoo>=0.6.1.5",
    "scikit-learn>=1.7.2",
    "scikit-posthocs>=0.11.4",
    "scipy>=1.16.2",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.5",
    "tabulate>=0.9.0",
]

[project.urls]
Homepage = "https://github.com/dynoptimization/pydmoo"
Repository = "https://github.com/dynoptimization/pydmoo"
Documentation = "https://pydmoo.readthedocs.io/"
"Source" = "https://github.com/dynoptimization/pydmoo"
"Issues" = "https://github.com/dynoptimization/pydmoo/issues"
"Changelog" = "https://github.com/dynoptimization/pydmoo/releases"

[dependency-groups]
dev = [
    "black>=25.9.0",
    "flake8>=7.3.0",
    "isort>=6.1.0",
    "mypy>=1.18.2",
    "pycodestyle>=2.14.0",
    "pydocstyle>=6.3.0",
    "ruff>=0.14.0",
]

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.ruff]
line-length = 120
indent-width = 4
exclude = [".venv"]
extend-exclude = ["tests"]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.mypy]
ignore_missing_imports = true

[tool.black]
line-length = 120
skip-magic-trailing-comma = true

[tool.isort]
line_length = 120
profile = "black"
include_trailing_comma = true

[tool.pytest]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
