[project]
name = "thecodecrate-pipeline"
version = "1.28.0"
description = "This package provides a pipeline pattern implementation"
readme = "README.md"
authors = [{ name = "TheCodeCrate", email = "loureiro.rg@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]
keywords = ["data pipelines"]
dependencies = []
requires-python = ">=3.13"

[project.urls]
repository = "https://github.com/thecodecrate/python-pipeline"
documentation = "https://thecodecrate.github.io/python-pipeline/"

[dependency-groups]
dev = [
    "black>=25.9.0",
    "bumpver>=2025.1131",
    "debugpy>=1.8.17",
    "ipykernel>=6.30.1",
    "mkdocs-autorefs>=1.4.3",
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-git-revision-date-localized-plugin>=1.4.7",
    "mkdocs-material>=9.6.21",
    "mkdocs-minify-plugin>=0.8.0",
    "mkdocstrings-python>=1.18.2",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 79

[tool.bumpver]
current_version = "1.28.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "feat: bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']
"src/thecodecrate_pipeline/__init__.py" = ['{version}']

[tool.setuptools.package-data]
"thecodecrate_pipeline" = ["py.typed"]

[tool.hatch.build.targets.wheel]
packages = ["src/thecodecrate_pipeline", "src/_lib"]
