[tool.poetry]
name = "readerCoerente"
version = "0.6.4"
description = "Package to load files saved by Cohaerentia Interferometric Interrogator."
authors = ["Marco Brunero <marco.brunero@cohaerentia.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
nptdms = "^1.10.0"
h5py = "^3.13.0"
scipy = "^1.15.2"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
matplotlib = "^3.10.1"
plotly = "^6.0.1"
nbformat = "^5.10.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
