[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=78.1.1", "wheel"]

[project]
authors = [{name = "Arturo Gutierrez Rubio Rojas", email = "agtzrubio@dagmalia.com"}]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Software Development :: Libraries :: Application Frameworks",
]
description = "Governed, Observable & Declarative Machine Learning Framework"
keywords = ["mlops", "machine learning", "framework", "governance", "observability", "mlflow"]
license = {text = "Apache-2.0"}
name = "godml"
readme = "README.md"
requires-python = ">=3.8,<=3.13"
version = "0.4.9"

dependencies = [
  # CLI & UX
  "typer==0.12.3",
  "click==8.1.3", # Explicit, aunque typer ya lo incluye
  "protobuf==4.25.8",
  "tensorflow==2.17.1",
  "urllib3>=2.5.0,<3", # Core ML
  "pandas==2.3.0",
  "numpy>=1.24.0,<2.0",
  "scikit-learn==1.5.0",
  "xgboost==3.0.2",
  "lightgbm==4.6.0",
  "mlflow==3.1.1", # Data Validation
  "pydantic==2.11.7", # Utilities
  "pyyaml==6.0.2",
  "rich==14.0.0", # AWS SDK
  "boto3>=1.40.0",
  "sagemaker==2.237.3",
  "gpt4all==2.8.2",
  "keras==3.11.3",
]

[project.scripts]
godml = "godml.godml_cli:main"

[project.optional-dependencies]
api = ["fastapi", "uvicorn[standard]", "joblib"]

[tool.setuptools.package-data]
"godml.utils" = ["README_TEMPLATE.txt", "DOCKERFILE_TEMPLATE.txt"]

[tool.setuptools.packages.find]
exclude = ["tests*", "venv*", "*.egg-info*"]
include = ["godml*"]
where = ["."]
