[project]
name = "cheap-settings"
version = "0.1.5"
description = "A lightweight, low footprint settings system"
readme = "README.md"
authors =[
    {name = "Evan Williams", email = "evanjpw@gmail.com"}
]
requires-python = ">=3.8"
license = "MIT"
keywords = [
    "config",
    "python",
    "application",
    "settings",
    "environment",
    "configuration",
    "env",
    "configurations",
    "environments",
    "python-config"
]
# See https://pypi.org/classifiers/
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = []

[project.urls]
# homepage = "https://"
# documentation = ""
repository = "https://github.com/evanjpw/cheap-settings"
# TODO: add a changelog
# changelog = "https://github.com/evanjpw/cheap-settings/blob/master/CHANGELOG.md"
issues = "https://github.com/evanjpw/cheap-settings/issues"

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=5.0.0",  # The latest version that supports Python 3.8 is 5.0.0
    "ruff>=0.13.3",
    "isort>=5.13.2"  # The latest version that supports Python 3.8 is 5.13.2
]

[tool.isort]
profile = "black"

[tool.hatch.build]
exclude = [
    "/.save",
    "/tests",
    "/examples"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
