[project]
name = "boring-math-number-theory"
version = "2.0.0"
readme = "README.rst"
requires-python = ">=3.13"
license = { file = "LICENSE" }
authors = [{ name = "Geoffrey R. Scheller", email = "geoffrey@scheller.com" }]
keywords = [
  "gcd",
  "lcm",
  "number-theory",
  "primes",
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Framework :: Pytest",
  "Intended Audience :: Education",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.13",
  "Typing :: Typed",
]
dependencies = [
  "pythonic-fp-circulararray>=6.0.0",
  "pythonic-fp-iterables>=5.1.2",
]
dynamic = ["description"]

[project.urls]
Changelog = "https://github.com/grscheller/boring-math-number-theory/blob/main/CHANGELOG.md"
Documentation = "https://grscheller.github.io/boring-math/number_theory/development/build/html"
Homepage = "https://grscheller.github.io/boring-math"
Source = "https://github.com/grscheller/boring-math-number-theory"

[project.optional-dependencies]
test = [
  "pytest>=8.4.1",
]

[build-system]
requires = ["flit_core>=3.12,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "boring_math.number_theory"

[tool.mypy]
enable_incomplete_feature = "NewGenericSyntax"
explicit_package_bases = true
implicit_reexport = false
local_partial_types = true
namespace_packages = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true

[tool.pylsp-mypy]
enabled = true
live-mode = true
dmypy = false
strict = true
report_progress = true

[tool.pytest.ini_options]
addopts = "-ra"
consider_namespace_packages = true
testpaths = ["tests/"]

[tool.ruff]
target-version = "py313"

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["C901"]
"**/*.py" = ["E741"]

[tool.ruff.format]
quote-style = "single"
docstring-code-line-length = 72
