[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "unifypy"
version = "2.0.4"
description = "UnifyPy 2.0 - Cross-platform Python app packaging tool"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
authors = [
  {name = "Junsen Huang"}
]
keywords = ["packaging", "pyinstaller", "installer", "windows", "macos", "linux"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  "pyinstaller>=6.0",
  "rich>=12.0",
  "requests>=2.28",
  "packaging>=21.0",
  "Pillow",
]

[project.scripts]
unifypy = "unifypy.__main__:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = [
  "unifypy",
  "unifypy.*",
]
