[project]
name = "zsynctech-studio-sdk"
version = "1.0.5"
description = "ZSyncTech Studio SDK for Python"
readme = "README.md"
authors = [
    { name = "Rodrigo Zavan", email = "rodrigo.zavan@zsynctech.com" }
]
requires-python = ">=3.13"
dependencies = [
    "appdirs>=1.4.4",
    "cachelib>=0.13.0",
    "cryptography>=46.0.2",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "pydantic>=2.12.0",
    "uuid7>=0.1.0",
]

[project.scripts]
zsynctech-studio-sdk = "zsynctech_studio_sdk:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
