# ref: <https://packaging.python.org/en/latest/specifications/pyproject-toml/>

[project]
name = "liblaf-apple"
description = "ðŸŽ A JAX and Warp library for differentiable physics simulation, featuring elastic energy models and finite element methods."
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
authors = [
  { name = "liblaf", email = "30631553+liblaf@users.noreply.github.com" },
]
keywords = []
classifiers = [
  # ref: <https://pypi.org/classifiers/>
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Typing :: Typed",
]
dependencies = [
  "beartype>=0.22,<0.23",  # TODO: Upgrade to JAX 0.7 when <https://github.com/patrick-kidger/equinox/issues/1084> is resolved.
  "chex>=0.1,<0.2",
  "cytoolz>=1,<2",
  "einops>=0.8,<0.9",
  "equinox>=0.13,<0.14",
  "felupe>=9,<10",
  "ipctk>=1,<2",
  "jax[cuda12]>=0.6,<0.7",
  "jaxtyping>=0.3,<0.4",
  "lazy-loader>=0.4,<0.5",
  "liblaf-grapes>=5,<6",
  "liblaf-melon>=0.7,<0.8",
  "lineax>=0.0.8,<0.0.9",
  "loguru>=0.7,<0.8",
  "matplotlib>=3,<4",
  "networkx>=3,<4",
  "numpy>=2,<3",
  "optax>=0.2,<0.3",
  "pyvista>=0.46,<0.47",
  "rich>=14,<15",
  "scikit-learn>=1,<2",
  "scipy>=1,<2",
  "wadler-lindig>=0.1,<0.2",
  "warp-lang>=1,<2",
]
dynamic = ["version"]

[project.urls]
"Changelog" = "https://github.com/liblaf/apple/blob/main/CHANGELOG.md"
"Documentation" = "https://liblaf.github.io/apple/"
"Homepage" = "https://github.com/liblaf/apple"
"Issue Tracker" = "https://github.com/liblaf/apple/issues"
"Release Notes" = "https://github.com/liblaf/apple/releases"
"Source Code" = "https://github.com/liblaf/apple"

[dependency-groups]
dev = [
  "icecream>=2,<3",
  "ipykernel>=6,<7",
  "liblaf-cherries>=0.5,<0.6",
  "marimo[recommended]>=0.16,<0.17",
  "sympy>=1,<2",
  "viztracer>=1,<2",
]
build = ["check-wheel-contents>=0.6,<0.7", "hatch>=1,<2", "twine>=6,<7"]
docs = ["liblaf-mkdocs-preset>=0.2,<0.3", "mkdocs>=1,<2"]
test = ["liblaf-pytest-preset>=0.1,<0.2", "pytest>=8,<9"]

[build-system]
requires = ["hatch-vcs", "hatchling"]
build-backend = "hatchling.build"

[tool.check-wheel-contents]
ignore = ["W002"]

[tool.coverage.report]
exclude_also = ["@wp.func"]

[tool.coverage.run]
branch = true
source = ["src"]

[tool.hatch.build.hooks.vcs]
version-file = "src/liblaf/apple/_version.py"

[tool.hatch.build.targets.sdist]
only-include = ["src"]

[tool.hatch.build.targets.wheel]
packages = ["src/liblaf"]

[tool.hatch.version]
source = "vcs"

[tool.pyright]
exclude = ["**/.*", "**/__pycache__", "**/marimo", "**/node_modules"]
extends = ".config/linters/pyrightconfig.json"
reportInvalidTypeForm = "none"

[tool.pytest.ini_options]
addopts = [
  "--doctest-modules",
  "--hypothesis-show-statistics",
  "--import-mode=importlib",
  "--showlocals",
  "--strict-config",
  "--strict-markers",
]
testpaths = ["benches", "src", "tests"]

[tool.ruff]
exclude = ["**/marimo/"]
extend = ".config/linters/.ruff.toml"

[tool.ruff.lint]
ignore = [
  "ANN201",
  "ANN202",
  "F722",
  "N802",
  "N803",
  "N806",
  "N815",
  "PLR0913",
  "RUF002",
]

[tool.uv]
default-groups = "all"
