[project]
name = "textual-utils"
version = "2.0.1"
description = "Utilities for use with the Textual package"
authors = [{ name = "Rafal Padkowski", email = "rafaelp@poczta.onet.pl" }]
requires-python = ">=3.13"
readme = "README.md"
license = "MIT"
dependencies = [
    "config",
    "i18n",
    "textual>=6.2.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
i18n = { git = "https://github.com/RafalPadkowski/i18n.git" }
config = { git = "https://github.com/RafalPadkowski/config.git" }
