[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "open-door-mcp"
version = "0.1.15"
description = "MCP service for controlling a door lock via MQTT broker (EMQX)."
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "paho-mqtt>=2.1.0",
    "fastmcp>=0.4.0",
    "pycryptodome>=2.23.0",
]


[tool.setuptools]
packages = ["JC_packet", "DoorLockController"]


[tool.setuptools.package-dir]
JC_packet = "JC_packet"
DoorLockController = "src/DoorLockController"

[project.scripts]
open_door_mcp = "DoorLockController.mcp_tools:run"



